// Generated by CoffeeScript 1.6.3
/*
Echo Forms - Hellicar & Lewis
Coding - Benjamin Blundell @ section9.co.uk
*/


(function() {
  var OpticalFlow;

  importScripts('/js/jsfeat-min.js');

  OpticalFlow = (function() {
    function OpticalFlow(dom_object) {
      this.dom_object = dom_object;
      this;
    }

    return OpticalFlow;

  })();

  this.startUp = function() {
    this.optical_flow = new OpticalFlow();
    return this;
  };

  this.onmessage = function(event) {
    switch (event.data.cmd) {
      case "startup":
        return startUp(event.data.data);
      default:
        return postMessage(event.data.cmd);
    }
  };

}).call(this);
